version: '3'
services:
    web:
        build: ./
        image: docker-hub-id/web:latest
    static_s:
        image: nginx
        volumes:
            - ./php_for_nginx/conf/:/etc/nginx/conf.d
            - ./php/src/index.html:/usr/share/nginx/index.html
        ports:
            - "80:80"
        environment:
            - NGINX_PORT=80
        depends_on:
            - php-apache-environment

    php-apache-environment:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./php/src/index.php:/var/www/pr/index.php
            - ./php/src/private:/var/www/pr/private
            - ./php/000-default.conf:/etc/apache2/sites-available/000-default.conf
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: appDB
        volumes:
            - ./:/docker-entrypoint-initdb.d
            - db_volume:/var/lib/mysql
        ports:
            - "9906:3306"
volumes:
    db_volume:
